# Generated by Django 3.1.2 on 2020-10-16 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dyqan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=25, verbose_name='Emri')),
                ('adresa', models.CharField(max_length=25, verbose_name='Adresa')),
                ('tel', models.CharField(max_length=25, verbose_name='Tel')),
                ('logo', models.ImageField(upload_to='static/media/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Dyqan',
                'verbose_name_plural': 'Dyqanet',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emri', models.CharField(max_length=25, verbose_name='Emri')),
                ('logo', models.ImageField(upload_to='static/media/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Keategori',
                'verbose_name_plural': 'Keategoritë',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Emri')),
                ('image', models.ImageField(upload_to='static/media/', verbose_name='Logo')),
                ('cmimi_blerje', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Cmimi i blerjes')),
                ('price', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Cmimi ')),
                ('sasia', models.IntegerField(verbose_name='Sasia')),
                ('njesia_matese', models.CharField(choices=[('kg', 'kilogram'), ('g', 'gram'), ('cope', 'cope'), ('l', 'liter')], default='kg', max_length=10)),
                ('dyqani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produktet', to='market.dyqan')),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produktet', to='market.kategori')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkte',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totali', models.DecimalField(decimal_places=2, default=0, max_digits=50, verbose_name='Cmimi total')),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fatura',
                'verbose_name_plural': 'Faturat',
            },
        ),
        migrations.CreateModel(
            name='ReceiptProducts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sasia', models.IntegerField(verbose_name='Sasia')),
                ('cmimi_total', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Cmimi total')),
                ('produkti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_products', to='market.product')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_products', to='market.receipt')),
            ],
        ),
    ]
